name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Backend

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'
    - name: Build jar
      run: mvn clean package
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag hbv501g-backend
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push the Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/hbv501g:hbv501g-backend